name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%2308519C&color_dots=%23EFF3FF,%23C6DBEF,%239ECAE1,%236BAED6,%233182BD
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23C6DBEF&color_dots=%23161B22,%2308519C,%233182BD,%236BAED6,%239ECAE1

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
